### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by denisazevedo** [gucarletto/ra-language-pt-br#1]
Hi, getting module not found after installing ra-language-pt-br.

_RunKit_ is not able to find it either:

> Error: Cannot find module 'ra-language-pt-br'

[https://npm.runkit.com/ra-language-pt-br](https://npm.runkit.com/ra-language-pt-br)

**Comment by denisazevedo** [comment]
Temporary fork created to publish a valid npm packate:

https://www.npmjs.com/package/@denisazevedo/ra-language-pt-br

**Comment by gucarletto** [comment]
Fixed the errors based on your fork.
