### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by paulo9mv** [gucarletto/ra-language-pt-br#14]

**Comment by gucarletto** [comment]
I'm not working with react-admin anymore, so I'm not maintaining this anymore. If you want I can add you as a collaborator.

**Comment by paulo9mv** [comment]
I would like, please :)

**Comment by gucarletto** [comment]
Cool. I added you as a collaborator here. Send me your npm username so I can add you there too.

**Comment by paulo9mv** [comment]
Thank you, it's "paulo9mv"

**Comment by gucarletto** [comment]
Cool, I sent you an invite so you can launch new updates.
