### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cgarrotti** [gucarletto/ra-language-pt-br#2]
Not working, button SAVE appear: RA.ACTION.SAVE

**Comment by gucarletto** [comment]
The referred key exists. Try removing package-lock.json and node_modules and then npm install again. Take a look at this issue:
https://github.com/marmelab/react-admin/issues/3007

**Comment by cgarrotti** [comment]
I deleted the package-lock and did the npm install again, but the error remains.

My codesandbox:
https://codesandbox.io/s/material-demo-d66fk?file=/demo.js

**Comment by luankjs** [comment]
@cgarrotti property 'locale' is deprecated.
You should create the provider specifing the language or getting it from the browser

import { resolveBrowserLocale } from 'react-admin'
const i18nProvider = polyglotI18nProvider(locale => messages[locale], resolveBrowserLocale()) // or 'pt-br'

https://stackoverflow.com/questions/60391967/understanding-react-admin-translation

I had the same problem and solve it removing 'locale' and force 'pt-br' on provider creation
