### ISSUE TITLE
Missing translation for key: "ra.navigation.skip_nav" 

### ISSUE THREAD

**Issue by felipejh** [gucarletto/ra-language-pt-br#6]
The `skip_nav` attribute is missing in `navigation` key on `index.ts`.

Error on console:
![image](https://user-images.githubusercontent.com/37714181/112750686-6eb7a300-8fa0-11eb-8b17-b95f872e6a0f.png)

Error on lib:
![image](https://user-images.githubusercontent.com/37714181/112750760-d53cc100-8fa0-11eb-8568-3147ed4f7d2d.png)

Fix on the `ra-language-english`:
https://github.com/marmelab/react-admin/pull/5867

Thanks!

**Comment by gucarletto** [comment]
Added the missing translation tag. Available in version 1.3.5.

Thanks for reporting :)
