### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by evandroalvisi** [gucarletto/ra-language-pt-br#7]
I am receiving the message when building: Cannot find module: 'ra-language-pt-br'. Make sure this package is installed.

but it is installed...

**Comment by evandroalvisi** [comment]
my package.json

{
  "name": "admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "axios": "^0.21.1",
    "ra-data-json-server": "^3.14.1",
    "ra-language-pt-br": "1.3",
    "react": "^17.0.2",
    "react-admin": "^3.14.1",
    "react-dom": "^17.0.2",
    "react-router-redux": "^4.0.8",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.0.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by ramonribeiro96** [comment]
same thing here.

"dependencies": {
    "@material-ui/core": "^4.11.3",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/pickers": "^3.3.10",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "^12.8.3",
    "moment": "^2.29.1",
    "prop-types": "^15.7.2",
    "ra-language-pt-br": "^1.3.5",
    "react": "^17.0.2",
    "react-admin": "^3.14.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "web-vitals": "^1.1.1"
    }

**Comment by gucarletto** [comment]
Sorry guys, there was a problem on the release of version 1.3.5. Updating to 1.3.6 should work.
